config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'

  resources :bookings, only: [:new, :create, :show]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: "departure_airport_id", class_name: "Flight"
  has_many :arriving_flights, foreign_key: "arrival_airport_id", class_name: "Flight"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: 'Airport'
  belongs_to :arrival_airport, class_name: 'Airport'
  has_many :bookings

  scope :distinct_departure_dates, -> { select(:departure_date).distinct }

  def departure_date_formatted
    departure_date.strftime('%b %d, %Y')
  end

  def departure_time_formatted
    departure_time.strftime('%I:%M %p %Z')
  end

  def arrival_time
    departure_time + duration * 60
    # duration given in minutes
  end

  def arrival_date_formatted
    arrival_time.strftime('%b %d, %Y')
  end

  def arrival_time_formatted
    arrival_time.strftime('%I:%M %p %Z')
  end

  def duration_formatted
    hours = duration / 60
    minutes = duration % 60
    "#{hours}h #{minutes}m"
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    params[:passengers].to_i.times { @booking.passengers.build }
    @selected_flight = Flight.find(params[:flight_id])
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      redirect_to @booking
      PassengerMailer.with(booking: @booking).confirmation_email.deliver_now!
    else
      @selected_flight = Flight.find(params[:booking][:flight_id])
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_default_params, only: [:index]

  def index
    @flights = Flight.all
    @search_results = search_flights(flight_params) if params
  end

  private

  def flight_params
    params.permit(:departure_airport_id, :arrival_airport_id, :departure_date, :passengers, :commit)
  end

  def search_flights(flight_params)
    Flight.where(departure_airport_id: flight_params[:departure_airport_id])
          .where(arrival_airport_id: flight_params[:arrival_airport_id])
          .where(departure_date: flight_params[:departure_date])
  end

  def set_default_params
    params[:departure_airport_id] ||= 1
    params[:arrival_airport_id] ||= 10
    params[:departure_date] ||= '2022-12-20'
    params[:passengers] ||= 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="bookings-new">
  <h1>New Booking</h1>
  
  <%= form_with model: @booking do |booking_form| %>
    <%= render partial: "shared/flight_info", locals: {flight: @selected_flight} %>
    <%= booking_form.hidden_field :flight_id, value: @selected_flight.id %>
  
    <div class="passengers-form">
      <h3>Passenger Information</h3>
      <ul>
        <%= booking_form.fields_for :passengers do |passenger_form| %>
          <li>
            <div class="passenger-name">
              <%= passenger_form.label :name, 'Name: ' %>
              <%= passenger_form.text_field :name %>
            </div>
            <div class="passenger-email">
              <%= passenger_form.label :email, 'Email: ' %>
              <%= passenger_form.email_field :email %>
            </div>
          </li>
        <% end %>
      </ul>
      <%= booking_form.submit "Book" %>
    </div>
  <% end %>

  <% if @booking.errors.any? %>
    <% @booking.errors.full_messages.each do |message| %>
      <div class="error-msg"><%= message %></div>
    <% end %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="bookings-show">
  <h1>Booking Information</h1>
  
  <h3>Flight</h3>
  <%= render partial: "shared/flight_info", locals: {flight: @booking.flight} %>

  <% if @booking.passengers.length > 1 %>
    <h3>Passengers</h3>
  <% else %>
    <h3>Passenger</h3>
  <% end %>

  <div class="passengers">
    <% @booking.passengers.map do |passenger| %>
      <ul>
        <li><%= "#{passenger[:name]}, #{passenger[:email]}" %></li>
      </ul>
    <% end %>
  </div>
</div>

app/views/flights/index.html.erb
<div class="flights-index">
  <h1>Search for Flights</h1>
  
  <%= form_with model: @flight, method: :get do |form| %>
    <%= form.label :departure_airport_id, "Departure Airport: " %>
    <%= form.collection_select :departure_airport_id, Airport.order(:city), :id, :city, selected: params[:departure_airport_id] %>
  
    <%= form.label :arrival_airport_id, "Arrival Airport: " %>
    <%= form.collection_select :arrival_airport_id, Airport.order(:city), :id, :city, selected: params[:arrival_airport_id] %>
  
    <%= form.label :departure_date, "Date: " %>
    <%= form.collection_select :departure_date, @flights.distinct_departure_dates, :departure_date, :departure_date_formatted, selected: params[:departure_date] %>
  
    <%= form.label :passengers, "Number of Passengers: " %>
    <%= form.number_field :passengers, in: 1..4, value: params[:passengers]  %>
  
    <%= form.submit "Search" %>
  <% end %>
  
  <% if params[:commit] %>
    <% if @search_results.any?%>
      <%= form_with url: new_booking_path, method: :get do |form| %>
        <div class="search-result">
          <% @search_results.each do |flight| %>
            <div class="radio-button">
              <%= form.radio_button :flight_id, flight.id %>
              <%= form.label :flight_id, flight.number %>
            </div>
            <%= render partial: "shared/flight_info", locals: {flight: flight} %>
            <%= form.hidden_field :passengers, value: params[:passengers]%>
          <% end %>
        </div>
        <%= form.submit "Select Flight" %>
      <% end %>
    <% else %>
      <p>No flights found.</p>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Odin Flight Booker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application',
      'https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap',
      media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="header">
      <div class="root"><%= link_to "Odin Flight Booker", root_path %></div>
    </div>

    <div class="body">
      <%= yield %>
    </div>

    <div class="footer">
      <p>Copyright © <a href="https://github.com/jp524">JP</a> 2022</p>
    </div>
  </body>
</html>

app/views/shared/_flight_info.html.erb
<div class="flight-info">
  <ul>
    <li>Departing from: <%= "#{flight.departure_airport[:code]} on #{flight.departure_date_formatted} at #{flight.departure_time_formatted}" %></li>
    <li>Arriving in: <%= "#{flight.arrival_airport[:code]} on #{flight.arrival_date_formatted} at #{flight.arrival_time_formatted}" %></li>
    <li>Flight duration: <%= flight.duration_formatted %></li>
  </ul>
</div>